### ISSUE TITLE
svviz seems to take a lot of time on some SV's

### ISSUE THREAD

**Issue by gatoravi** [svviz/svviz#16]
Hi Noah,

Is there a limit on the SV size that can be visualized with svviz. I’ve been having a little bit of trouble visualizing some deletions/inversions >20kb, probably because of the large number of reads spanning these breakpoints.

This is on Whole Genome Sequencing data on a tumor/normal pair. I assume it’s just that the big events have a lot of reads which takes a while, for e.g I got this message "LOTS OF READS IN REGION:8 43094789 43094790 1227892” for one of the events. 

I’ve only waited for a maximum of ~8 hours for some of these events, perhaps I should wait longer? I was wondering if this is expected? Have you thought about downsampling reads perhaps?

Thanks,
Avi

**Comment by nspies** [comment]
Hrm, you should be no where close to the practical limit of SVs that can be visualized with svviz (should be more over 10mb). The "lots of reads in region” message suggests you have lots of repetitively mapping reads. I’m guessing it’s choking on the step where it’s trying to find the read mates, which are strewn about the genome — if the mates fall in regions of high sequence coverage (eg the bit of chromosome 8 in your example), svviz has to walk through the bam from the closest index point in order to find the read mate of interest, which could take a while.

The easiest solution, if you haven’t already tried this, would be to change the mapq cutoffs; it shouldn’t try to find the mates of reads with low mapq (this only works with --min-mapq, not --pair-min-mapq).

A more general solution would be to give you the option of skipping reads whose mates fall in regions of high coverage. Let me know if the --min-mapq solution doesn’t work, as adding this option should be relatively straightforward.

Should probably improve the documentation around this.

**Comment by gatoravi** [comment]
Thanks for the feedback, it does make sense that looking for reads in regions of high coverage could choke.

I tried the -q option(same as --min-mapq) on a deletion of length 47KB, it's taken more than 12 hours at the realign step and is still running, the exact command that I used is below,

``` bash
./myenv/bin/svviz -t del -b $bam1 -b $bam2 $fasta 2 16332715 16379722 \
    --no-web -e 2:16332715-16379722.pdf --summary 2:16332715-16379722.out -q 25
```

**Comment by nspies** [comment]
Just to make sure I'm fixing the right problem, can you post the output from svviz so that I know which step it's choking on?

Also, if mapq goes up to 60 in your files, could you just try it with `-q 60`? Just let me know if it takes more than 5 minutes with that option.

**Comment by gatoravi** [comment]
Ok, I checked to make sure that the BAM file has mapping qualities going from [0-60]. I then ran svviz with a cutoff of 60, here's the output after running for about an hour,

```
   14491  - d0cb366d4727467789c9ddd05f6fde3a
   14492   To-match: 18151, min-mapq: 60.0
   14493   0 18151 starting...
   14494   LOTS OF READS IN REGION:1 121485089 121485090 592721
   14495   1000 18151 9.32695388794
   14496   LOTS OF READS IN REGION:19 27732016 27732017 241936
   14497   2000 18151 4.53237199783
   14498   3000 18151 2.15582108498
   14499   4000 18151 1.64572691917
   14500   5000 18151 1.2749710083
   14501   6000 18151 1.17867612839
   14502   7000 18151 1.2287979126
   14503   8000 18151 1.29893708229
   14504   9000 18151 0.962944030762
   14505   LOTS OF READS IN REGION:10 42388361 42388362 348819
   14506   10000 18151 6.26318287849
   14507   11000 18151 1.27597618103
   14508   12000 18151 1.91607689857
   14509   13000 18151 0.817262887955
   14510   LOTS OF READS IN REGION:2 92315360 92315361 149283
   14511   LOTS OF READS IN REGION:10 42384481 42384482 106801
   14512   14000 18151 4.58829712868
   14513   15000 18151 4.86111187935
   14514   16000 18151 0.904628038406
   14515   17000 18151 1.23500204086
   14516   18000 18151 1.66472911835
   14517   missing pairs: 350
   14518   ** Supplementary alignments found: these alignments (with sam flag 0x800) **
   14519   ** are poorly documented among mapping software and may result in missing **
   14520   ** portions of reads; consider using the --include-supplementary command line **
   14521   ** argument if you think this is happening                                **
   14522   time to find reads and mates:49.6526730061
   14523   number of reads found: 18432
   14524 * Realigning reads *
```

**Comment by nspies** [comment]
Okay, so for this run, it seems to be having problems with the realignment step, not pulling in mates as I originally thought.

I tried running the region you're looking at on one of my BAM files and it took 45 seconds to complete running (obviously my bam doesn't have reads supporting the deletion allele, but that shouldn't dramatically affect run time).

Any chance you can share the relevant read data with me? If you use the `--save-reads` option, you can create a BAM file with only the reads svviz is using for the variant of interest (50,000 reads from a random location on chromosome 1 plus the reads near the event). The file should be roughly 25MB, I think. You could send me a link to the file (box or dropbox or whatever), or I can send you a link for you to upload to.

**Comment by nspies** [comment]
So that worked fine for me with the files you sent me. I used this command:

`svviz -t del -b 2\:16332715-16379722.0.sorted.bam -b 2\:16332715-16379722.1.sorted.bam hg19.fasta chr2 16332715 16379722 -e 2_16332715-16379722.png --skip-cigar`

Can you see if you're still having the same problem if you run with the files you sent me, instead of the original BAMs? I'm kind of at a loss for why you might be having this problem.

Just to confirm, after the `* Realigning reads *` line in the svviz output, you're getting the progress bar for the realignment step, correct?

**Comment by gatoravi** [comment]
Yeah you're right, when I run it on just the files that I shared it works fine at my end as well. It's something to do with the original BAM file, 
The last line that I see in the logs before the long wait is

```
 85 * Realigning reads * 
 86   Removed 19 reads with only degenerate nucleotides ('N')
```

I don't see any progress bars. Perhaps I can use a  Python debugger to see whats being executed?

**Comment by nspies** [comment]
Sure, let me know if you track down the problem. You'll probably want to use `--processes 1` so that you don't have to debug across processes.

**Comment by nspies** [comment]
I'm going to close this issue as it appears to be difficult to reproduce and there's a workaround that works for you. Please let me know if you have any more information on the original issue.

**Comment by gatoravi** [comment]
Ok, thanks. Not sure if this is related but when I run it with `--processes 1` I get a different error,
#Command

```
svviz -t del -b $bam1 -b $bam2 all_sequences.fa 2 16332715 16379722 --no-web -e 2:16332715-16379722.pdf --summary 2:16332715-16379722.out --processes 1
```

#Output

```
set(['A', 'C', 'T', 'G']) 100 AAGACAGTTGGGCAACTTCATGTGAAGCACGTTTCCCTCACTTCAGAATCCCTCCCTCTTGGAAGTGAACACAAGGACTTGGATGGTTCAGCTTCACTCT
set(['A', 'C', 'T', 'G']) 100 TGATAGCTGGCCTTTTTCAAAAGCATTCCGGCCTGCTAAACAGTGGCCTTTCATGATTTACAAGTTTGGAATCTTTGAGAATTTTCAACAATTAAGGTAC
set(['A', 'C', 'T', 'G']) 100 ACGTGTGAAGTTACAGTCCAGAGCAGGCACTGTCAGATAGTAACTCCAAAGGCTCAGGAGGAAACACTTGCTTTAGCTTAGCATGTCACTGTTTTCGAAG
Traceback (most recent call last):
  File "src/svviz/myenv/bin/svviz", line 9, in <module>
    load_entry_point('svviz==1.3.1', 'console_scripts', 'svviz')()
  File "src/svviz/myenv/lib/python2.7/site-packages/svviz/app.py", line 296, in main
    run(sys.argv)
  File "src/svviz/myenv/lib/python2.7/site-packages/svviz/app.py", line 267, in run
    runRemap(dataHub)
  File "src/svviz/myenv/lib/python2.7/site-packages/svviz/app.py", line 89, in runRemap
    sample.alnCollections = remap.do_realign(dataHub.variant, sample.reads, dataHub.args.processes)
  File "src/svviz/myenv/lib/python2.7/site-packages/svviz/remap.py", line 198, in do_realign
    refalignments = do1remap(variant.chromParts("ref"), reads, processes)
  File "src/svviz/myenv/lib/python2.7/site-packages/svviz/remap.py", line 141, in do1remap
    aln = chooseBestAlignment(read, remapped[read.seq], chromPartsCollection)
TypeError: list indices must be integers, not str
```

Just posting here for posterity's sake, I'll let you know if I figure out the original issue.

**Comment by nspies** [comment]
Alright, that's a separate bug which should be fixed in the master

**Comment by gatoravi** [comment]
Just an update - We're still seeing this happen with some SV's. The program runs at 100% CPU for hours but it's not able to finish running. Not sure, if this has something to with our internal setup here but we've seen this across multiple BAMs by a couple of users.

Running strace on a process shows this log,

```
.....
.....
lstat(/dev/shm/sem.nAEKMZ, 0x7fff59d01560) = -1 ENOENT (No such file or directory)
open(/dev/shm/sem.nAEKMZ, O_RDWR|O_CREAT|O_EXCL, 0600) = 13
write(13, 10000000000000000000000000000000, 32) = 32
mmap(NULL, 32, PROT_READ|PROT_WRITE, MAP_SHARED, 13, 0) = 0x7f749d048000
link(/dev/shm/sem.nAEKMZ, /dev/shm/sem.mp2510-71) = 0
fstat(13, {st_mode=S_IFREG|0600, st_size=32, ...}) = 0
unlink(/dev/shm/sem.nAEKMZ)           = 0
close(13)                               = 0
unlink(/dev/shm/sem.mp2510-71)        = 0
write(1,  total time elapsed: 3.53334498..., 71  total time elapsed: 3.53334498405
used rsvg-convert to export to PDF
) = 71
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f749d01c9d0) = ? ERESTARTNOINTR (To be restarted)
--- SIGPROF (Profiling timer expired) @ 0 (0) ---
rt_sigreturn(0x1b)                      = 56
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f749d01c9d0) = ? ERESTARTNOINTR (To be restarted)
--- SIGPROF (Profiling timer expired) @ 0 (0) ---
rt_sigreturn(0x1b)                      = 56
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f749d01c9d0) = ? ERESTARTNOINTR (To be restarted)
--- SIGPROF (Profiling timer expired) @ 0 (0) ---
rt_sigreturn(0x1b)                      = 56
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f749d01c9d0) = ? ERESTARTNOINTR (To be restarted)
--- SIGPROF (Profiling timer expired) @ 0 (0) ---
rt_sigreturn(0x1b)                      = 56
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f749d01c9d0) = 4874
wait4(4874, 0x7fff59d02664, WNOHANG, NULL) = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f749d01c9d0) = ? ERESTARTNOINTR (To be restarted)
--- SIGPROF (Profiling timer expired) @ 0 (0) ---
rt_sigreturn(0x1b)                      = 56
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f749d01c9d0) = ? ERESTARTNOINTR (To be restarted)
--- SIGPROF (Profiling timer expired) @ 0 (0) ---
rt_sigreturn(0x1b)                      = 56
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f749d01c9d0) = ? ERESTARTNOINTR (To be restarted)
--- SIGPROF (Profiling timer expired) @ 0 (0) ---
rt_sigreturn(0x1b)                      = 56
....
```

and then there's a lot of lines(~100K) which have the `clone()` and `rt_sigreturn()` calls.

Googling around brings [this](https://mail.python.org/pipermail/cplusplus-sig/2015-April/017248.html) and [this](http://caml.inria.fr/mantis/view.php?id=5893) up, we may have to fly you up here;) Glad to try any suggestions.

**Comment by nspies** [comment]
Just to confirm, you're using the `--skip-cigar` option, right?

**Comment by nspies** [comment]
I think I lost the thread a bit -- can you post the full output from svviz, including the command you're using to run it? If it's crapping out at the realignment step, I might need the original BAM file in order to do some more debugging. Would it be possible to send me the BAM somehow?

**Comment by apregier** [comment]
I don't think it is necessarily failing in realignment - it seems to hang in a number of different places.  I just ran the following command and it seems to be hanging on \* Exporting views *.  By hanging, I mean spinning at 100% cpu and not really doing anything.  If you connect to the process with strace it spits out the clone() and rt_sigreturn() over and over again.
If it is a kernel issue, we may be hosed...unless we could figure out what is causing the problem and compile that without the 'profile' option?
Command:

```
svviz --type batch --export svviz/cosmic --summary svviz/cosmic.summary --include-supplementary --processes 1 --skip-cigar -b normal_highcov.bam -b tumor_highcov.bam all_sequences.fa deletions_inversions.vcf"
```

Output:

```
Namespace(_parser=ArgumentParser(prog='svviz', usage='%(prog)s [options] [demo] [ref breakpoint...] [ref vcf]', description='svviz version 1.3.2', version=None, formatter_class=<class 'argparse.RawTextHelpFormatter'>, conflict_handler='error', add_help=True), aln_quality=None, annotations=None, bam=['normal_highcov.bam', 'tumor_highcov.bam'], breakpoints=['deletions_inversions.vcf'], context=0, dotplots=False, export='svviz/cosmic', fasta=None, flanks=False, format=None, include_supplementary=True, lenient=False, max_multimapping_similarity=0.95, max_reads=None, min_mapq=0, no_web=True, open_exported=False, orientation=None, pacbio=False, pair_min_mapq=0, port=None, processes=1, ref='all_sequences.fa', save_reads=None, save_state=None, skip_cigar=True, summary='svviz/cosmic.summary', thicker_lines=False, type='batch', verbose=3)
* Sampling reads to calculate Insert Size Distributions *
 > normal_highcov <
  counts +/-:49411  -/+:590    +/+:0      -/-:0      unpaired:0
  insert size mean: 322.08 std: 79.20
  valid orientations: +-
  Using search distance: 480
 > tumor_highcov <
  counts +/-:48510  -/+:1491   +/+:0      -/-:0      unpaired:0
  insert size mean: 303.36 std: 88.02
  valid orientations: +-
  Using search distance: 479
 Using align distance: 655
* Loading variants from input VCF file *
 Loaded 26 variants
* Running for variant 1/26 Deletion::1:9,417,727-9,437,123(19396) *
* Loading reads and finding mates *
 - normal_highcov
  To-match: 22902, min-mapq: 0
  0 22902 Finding mate pairs...
  LOTS OF READS IN MATE-PAIR REGION:2 33141308 33141309 169730
  LOTS OF READS IN MATE-PAIR REGION:6 160521754 160521755 109550
  LOTS OF READS IN MATE-PAIR REGION:11 51590451 51590452 224305
  LOTS OF READS IN MATE-PAIR REGION:2 33141547 33141548 376380
  1000 22902 129.591683149
  2000 22902 1.9468729496
  3000 22902 2.2770819664
  LOTS OF READS IN MATE-PAIR REGION:2 33141619 33141620 354167
  4000 22902 40.9575459957
  5000 22902 5.28120398521
  LOTS OF READS IN MATE-PAIR REGION:2 33141319 33141320 398687
  6000 22902 46.2647850513
  LOTS OF READS IN MATE-PAIR REGION:2 33141420 33141421 170170
  LOTS OF READS IN MATE-PAIR REGION:12 66451372 66451373 528258
  LOTS OF READS IN MATE-PAIR REGION:15 77910867 77910868 157699
  7000 22902 107.953973055
  8000 22902 4.08516192436
  9000 22902 17.4634859562
  10000 22902 4.25651812553
  LOTS OF READS IN MATE-PAIR REGION:2 33141466 33141467 393021
  11000 22902 40.2546839714
  12000 22902 1.68355584145
  13000 22902 1.4518020153
  14000 22902 2.08066916466
  15000 22902 3.05457997322
  LOTS OF READS IN MATE-PAIR REGION:2 33091951 33091952 252492
  16000 22902 34.2577848434
  17000 22902 1.06766104698
  18000 22902 2.656042099
  19000 22902 10.8296208382
  20000 22902 4.15118217468
  21000 22902 1.72145199776
  22000 22902 1.76672387123
  missing pairs: 23
  time to find reads and mates:481.862607956
  number of reads found: 23379
 - tumor_highcov
  To-match: 922, min-mapq: 0
  0 922 Finding mate pairs...
  LOTS OF READS IN MATE-PAIR REGION:2 33141422 33141423 181491
  missing pairs: 7
  time to find reads and mates:31.3594670296
  number of reads found: 1092
* Realigning reads *
  time for realigning:118.560303926
  time for realigning:4.96222901344
* Assigning reads to most probable alleles *
 Time for disambiguation: 4.17s
 Time for disambiguation: 0.99s
* Rendering tracks *
* Exporting views *
```

**Comment by nspies** [comment]
A few things to try, if you don't mind:

(1) I've created a branch on github that will print out a little more debugging info; I'm at a loss for what might be happening, as svviz does very little of interest after exporting views (really just records some summary statistics), but it's possible it's hanging there for some reason. To use this branch, do:

`pip install -U git+git://github.com/svviz/svviz.git@debug16`

Then run svviz as before, but with `--verbose 9`, and send me the output.

(2) Try running svviz without the `--export`, and instead with just the `--no-web` option (just in case rsvg-convert is doing something funky).

(3) Have you gotten this error to occur when running locally? If you can run svviz until it hits that infinite loop, you can hit ctrl-c from the terminal and look at the python stack trace which would be more useful than strace (?). Or if it's doesn't exit with a keyboard interrupt, we'd at least know it's because of some external code running.

(4) It would be helpful if you could see about getting me the input BAM, fasta and vcf. Send me an email if this might be possible (I'm guessing these are patient samples so may need to be treated a bit more carefully)

**Comment by apregier** [comment]
I just ran locally without --export, and it progressed past the first variant.  I ran again with --export to see if I could get a stack trace as you suggested, and I got the following error during Exporting Variants.  I guess this is just indicating that I don't have enough memory locally (8 Gb).  I haven't tried installing the debug branch yet, I will try that next.

```
* Exporting views *
Traceback (most recent call last):
  File "/gscmnt/gc8001/info/model_data/aregier/bin/svviz/venv/bin/svviz", line 9, in <module>
    load_entry_point('svviz==1.3.2', 'console_scripts', 'svviz')()
  File "/gscmnt/gc8001/info/model_data/aregier/bin/svviz/venv/lib/python2.7/site-packages/svviz/app.py", line 296, in main
    run(sys.argv)
  File "/gscmnt/gc8001/info/model_data/aregier/bin/svviz/venv/lib/python2.7/site-packages/svviz/app.py", line 278, in run
    runDirectExport(dataHub)
  File "/gscmnt/gc8001/info/model_data/aregier/bin/svviz/venv/lib/python2.7/site-packages/svviz/app.py", line 153, in runDirectExport
    exportData = export.convertSVG(exportData, exportFormat)
  File "/gscmnt/gc8001/info/model_data/aregier/bin/svviz/venv/lib/python2.7/site-packages/svviz/export.py", line 240, in convertSVG
    if not canConvertSVGToPDF():
  File "/gscmnt/gc8001/info/model_data/aregier/bin/svviz/venv/lib/python2.7/site-packages/svviz/export.py", line 229, in canConvertSVGToPDF
    subprocess.check_call("webkitToPDF", stderr=subprocess.PIPE, shell=True)
  File "/gscmnt/gc2607/mardiswilsonlab/aramu/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/gscmnt/gc2607/mardiswilsonlab/aramu/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/gscmnt/gc2607/mardiswilsonlab/aramu/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/gscmnt/gc2607/mardiswilsonlab/aramu/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

**Comment by nspies** [comment]
If you’re running out of memory locally, you might want to just start the jobs on the cluster in an interactive shell — that way you’ll know you’re using the exact same setup as you would be when running the batch jobs (it looks like your local computer is a mac and the batch jobs are being run on linux).

On Oct 8, 2015, at 2:25 PM, Allison Penner Regier <notifications@github.com<mailto:notifications@github.com>> wrote:

I just ran locally without --export, and it progressed past the first variant. I ran again with --export to see if I could get a stack trace as you suggested, and I got the following error during Exporting Variants. I guess this is just indicating that I don't have enough memory locally (8 Gb). I haven't tried installing the debug branch yet, I will try that next.
- Exporting views *
  Traceback (most recent call last):
  File "/gscmnt/gc8001/info/model_data/aregier/bin/svviz/venv/bin/svviz", line 9, in <module>
    load_entry_point('svviz==1.3.2', 'console_scripts', 'svviz')()
  File "/gscmnt/gc8001/info/model_data/aregier/bin/svviz/venv/lib/python2.7/site-packages/svviz/app.py", line 296, in main
    run(sys.argv)
  File "/gscmnt/gc8001/info/model_data/aregier/bin/svviz/venv/lib/python2.7/site-packages/svviz/app.py", line 278, in run
    runDirectExport(dataHub)
  File "/gscmnt/gc8001/info/model_data/aregier/bin/svviz/venv/lib/python2.7/site-packages/svviz/app.py", line 153, in runDirectExport
    exportData = export.convertSVG(exportData, exportFormat)
  File "/gscmnt/gc8001/info/model_data/aregier/bin/svviz/venv/lib/python2.7/site-packages/svviz/export.py", line 240, in convertSVG
    if not canConvertSVGToPDF():
  File "/gscmnt/gc8001/info/model_data/aregier/bin/svviz/venv/lib/python2.7/site-packages/svviz/export.py", line 229, in canConvertSVGToPDF
    subprocess.check_call("webkitToPDF", stderr=subprocess.PIPE, shell=True)
  File "/gscmnt/gc2607/mardiswilsonlab/aramu/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(_popenargs, *_kwargs)
  File "/gscmnt/gc2607/mardiswilsonlab/aramu/lib/python2.7/subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "/gscmnt/gc2607/mardiswilsonlab/aramu/lib/python2.7/subprocess.py", line 710, in **init**
    errread, errwrite)
  File "/gscmnt/gc2607/mardiswilsonlab/aramu/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
  OSError: [Errno 12] Cannot allocate memory

**Comment by apregier** [comment]
Ok - it does not exit with a keyboard interrupt.

**Comment by apregier** [comment]
I did get a core dump, which is 4.5 Gb

**Comment by apregier** [comment]
Looking at the core dump with gdb:

```
Program terminated with signal 3, Quit.
#0  0x00002ad0ec03d9f6 in __libc_fork () at ../nptl/sysdeps/unix/sysv/linux/x86_64/../fork.c:130
```

I don't know if this is helpful or not.

**Comment by gatoravi** [comment]
Same on my end, the interactive job does not terminate with a Ctrl-C, I had to kill the process using `top`. There is just one running process when it hangs if that helps at all.
This is my `site-packages` folder if there's any outdated packages we should be looking into,

```
 svviz --version
svviz version 1.3.3dev

 /bin/ls
Flask-0.10.1.dist-info     flask                        markupsafe                    pyfaidx-0.4.2.dist-info    six-1.10.0.dist-info             wheel
Jinja2-2.8.dist-info       itsdangerous-0.24.dist-info  numpy                         pysam                      six.py                           wheel-0.24.0.dist-info
MarkupSafe-0.23.dist-info  itsdangerous.py              numpy-1.10.0.post2.dist-info  pysam-0.8.3.dist-info      six.pyc
Werkzeug-0.10.4.dist-info  itsdangerous.pyc             pip                           requests                   ssw
_markerlib                 jinja2                       pip-7.1.2.dist-info           requests-2.8.0.dist-info   svviz
easy_install.py            joblib                       pkg_resources                 setuptools                 svviz-1.3.3.dev0-py2.7.egg-info
easy_install.pyc           joblib-0.8.4.dist-info       pyfaidx                       setuptools-18.2.dist-info  werkzeug
```

**Comment by nspies** [comment]
Did you get the full batch job to run on the cluster without the export working? The extra logging info might be helpful, but I’m guessing there’s something wrong with rsvg-convert. If it runs fine sans conversion, I can try to add support for wkhtmltopdf instead of rsvg-convert.

On Oct 8, 2015, at 3:38 PM, Avinash Ramu <notifications@github.com<mailto:notifications@github.com>> wrote:

Same on my end, the interactive job does not terminate with a Ctrl-C, I had to kill the process using top. There is just one running process when it hangs if that helps at all.
This is my site-packages folder if there's any outdated packages we should be looking into,

 svviz --version
svviz version 1.3.3dev

 /bin/ls
Flask-0.10.1.dist-info     flask                        markupsafe                    pyfaidx-0.4.2.dist-info    six-1.10.0.dist-info             wheel
Jinja2-2.8.dist-info       itsdangerous-0.24.dist-info  numpy                         pysam                      six.py                           wheel-0.24.0.dist-info
MarkupSafe-0.23.dist-info  itsdangerous.py              numpy-1.10.0.post2.dist-info  pysam-0.8.3.dist-info      six.pyc
Werkzeug-0.10.4.dist-info  itsdangerous.pyc             pip                           requests                   ssw
_markerlib                 jinja2                       pip-7.1.2.dist-info           requests-2.8.0.dist-info   svviz
easy_install.py            joblib                       pkg_resources                 setuptools                 svviz-1.3.3.dev0-py2.7.egg-info
easy_install.pyc           joblib-0.8.4.dist-info       pyfaidx                       setuptools-18.2.dist-info  werkzeug

**Comment by gatoravi** [comment]
Nope, I haven't been able to get the full batch to work. Even without the `--export` it hangs.

**Comment by nspies** [comment]
I think I’ve come the end of ideas I have for remotely debugging this. If you decide it’s okay to send me one of the input BAMs that’s causing the problem, I’ll see if I can replicate the issue here.

On Oct 8, 2015, at 6:30 PM, Avinash Ramu <notifications@github.com<mailto:notifications@github.com>> wrote:

Nope, I haven't been able to get the full batch to work. Even without the --export it hangs.

**Comment by apregier** [comment]
I'll look into it - it is cell line data so we might be able to, but I need to check.  I am also trying to set up a vm with a newer OS to see if it replicates there, but it is taking a while to get it all set up.  One note as I was working on setting up the vm - it looks like there is a dependency on zlib1g-dev that isn't noted in the documentation.

**Comment by apregier** [comment]
I've finally gotten the vm going, and it looks promising, but I'm having to run without --export.  Even though I installed librsvg2-dev, it gave the error:

```
/bin/sh: 1: rsvg-convert: not found
Can't find rsvg-convert; make sure you have librsvg installed
Traceback (most recent call last):
  File "/usr/local/bin/svviz", line 9, in <module>
    load_entry_point('svviz==1.3.2', 'console_scripts', 'svviz')()
  File "/usr/local/lib/python2.7/dist-packages/svviz/app.py", line 296, in main
    run(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/svviz/app.py", line 278, in run
    runDirectExport(dataHub)
  File "/usr/local/lib/python2.7/dist-packages/svviz/app.py", line 155, in runDirectExport
    outf.write(exportData)
TypeError: expected a character buffer object
```

Any ideas?  The vm is on debian trusty.
Update: Damn, I just ran out of memory.  I was only able to get a 8Gb vm.

**Comment by nspies** [comment]
Sounds like I need to do some memory profiling -- I have lots of RAM on my various dev/test boxes, but svviz should fit in 8GB of RAM, ideally. Lots of things are getting fixed up, except not your original issue (yet!)
